### ISSUE TITLE
undefined: mapset

### ISSUE THREAD

**Issue by skerbis** [christophboecker/geolocation#12]
**ErrorException:** Undefined variable: mapset
**File:** redaxo/src/addons/geolocation/lib/yform/dataset/mapset.php
**Line:** 265

<details>
<summary>Stacktrace</summary>

| Function                                           | File                                                                       | Line     |
| -------------------------------------------------- | -------------------------------------------------------------------------- | -------- |
| rex_error_handler::handleError                     | redaxo/src/addons/geolocation/lib/yform/dataset/mapset.php                 | 265      |
| Geolocation\mapset->getLayerset                    | redaxo/src/addons/geolocation/lib/yform/dataset/mapset.php                 | 434      |
| Geolocation\mapset->parse                          | rex:///module/39/output                                                    | 21       |
| require                                            | redaxo/src/addons/structure/plugins/content/lib/article_content_base.php   | 516      |
| rex_article_content_base->{closure}                | redaxo/src/addons/structure/plugins/content/lib/article_content_base.php   | 518      |
| rex_article_content_base->getStreamOutput          | redaxo/src/addons/structure/plugins/content/lib/article_content_editor.php | 272      |
| rex_article_content_editor->getWrappedModuleOutput | redaxo/src/addons/structure/plugins/content/lib/article_content_editor.php | 85       |
| rex_article_content_editor->outputSlice            | redaxo/src/addons/structure/plugins/content/lib/article_content_base.php   | 720      |
| rex_article_content_base->renderSlices             | redaxo/src/addons/structure/plugins/content/lib/article_content_base.php   | 428      |
| rex_article_content_base->getArticle               | redaxo/src/addons/structure/plugins/content/lib/article_content.php        | 105      |
| rex_article_content->getArticle                    | redaxo/src/addons/structure/plugins/content/pages/content.edit.php         | 35       |
| include                                            | redaxo/src/core/lib/packages/package.php                                   | 285      |
| rex_package->includeFile                           | redaxo/src/core/lib/be/controller.php                                      | 485      |
| rex_be_controller::{closure}                       | redaxo/src/core/lib/util/timer.php                                         | 63       |
| rex_timer::measure                                 | redaxo/src/core/lib/be/controller.php                                      | 486      |
| rex_be_controller::includePath                     | redaxo/src/core/lib/be/controller.php                                      | 432      |
| rex_be_controller::includeCurrentPageSubPath       | redaxo/src/addons/structure/plugins/content/pages/content.php              | 432      |
| include                                            | redaxo/src/core/lib/packages/package.php                                   | 285      |
| rex_package->includeFile                           | redaxo/src/core/lib/be/controller.php                                      | 485      |
| rex_be_controller::{closure}                       | redaxo/src/core/lib/util/timer.php                                         | 63       |
| rex_timer::measure                                 | redaxo/src/core/lib/be/controller.php                                      | 486      |
| rex_be_controller::includePath                     | redaxo/src/core/lib/be/controller.php                                      | 415      |
| rex_be_controller::includeCurrentPage              | redaxo/src/core/backend.php                                                | 238      |
| require                                            | redaxo/src/core/boot.php                                                   | 143      |
| require                                            | redaxo/index.php                                                           | 9        |

</details>
<details>
<summary>System report (REDAXO 5.13.1, PHP 7.4.26, MariaDB 10.2.39)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.13.1     |

| PHP           |            |
| ------------: | :--------- |
|       Version | 7.4.26     |
|       OPcache | yes        |
|        Xdebug | yes        |

| Database      |                 |
| ------------: | :-------------- |
|       Version | MariaDB 10.2.39 |
| Character set | utf8mb4         |

</details>

**Comment by christophboecker** [comment]
Ist wie vermutet: `$mapset` sollte  eigentlich`$this` sein. Korrigiert mit #13. Zudem den Namespace des AssetPacker in den Namespace Geolocation integriert.

**Comment by skerbis** [comment]
danke
