### ISSUE TITLE
Install verursacht Speicherüberlauf

### ISSUE THREAD

**Issue by iceman-fx** [christophboecker/geolocation#21]
Addon kann nicht installiert und verursacht beim Versuch immer einen Speicherüberlauf.
Allowed memory size of 134217728 bytes exhausted (tried to allocate 67092480 bytes)

07.02.2022, 10:18:59
Warning
tempnam(): open_basedir restriction in effect. File(/tmp) is not within the allowed path(s): (/home/www/web3/)
redaxo/src/addons/geolocation/install.php
111

07.02.2022, 10:18:59
Warning
unlink(): open_basedir restriction in effect. File() is not within the allowed path(s): (/home/www/web3/)
redaxo/src/addons/geolocation/install.php
110

07.02.2022, 10:18:59
Warning
rename(): open_basedir restriction in effect. File() is not within the allowed path(s): (/home/www/web3/)
redaxo/src/addons/geolocation/install.php
109

**Comment by christophboecker** [comment]
Um das zu testen, habe ich auf meinem Rechner (iMac, BigSur, MySQL 8.0.17, PHP 7.4.26) in einem leeren Redaxo (5.13.2, YForm 4.0.0) Geolocation installiert. Die Installation lief klaglos und ohne Fehler durch. 

Da habe ich erstmal keinen Pack-an für Fehlersuche. Scheint irgendwas mit Zugriffsrechten oder Hostimg-Konfiguration zu sein: https://stackoverflow.com/questions/1846882/open-basedir-restriction-in-effect-file-is-not-within-the-allowed-paths

Ich lasse das Issue noch mal offen für den Fall, dass sich weitere Hinweise ergeben.
