### ISSUE TITLE
Manual: Hinweis auf API-Key-Tausch der Demo-HERE-Karten 

### ISSUE THREAD

**Issue by christophboecker** [christophboecker/geolocation#23]
Das war mal in der Doku, ist wohl rausgefallen

**Comment by skerbis** [comment]
@christophboecker vielleicht macht es Sinn die Reihenfolge der "Karten" zu tauschen und Here an das Ende zu setzen

**Comment by christophboecker** [comment]
Warum? Das sind reine Demo-Daten. Der Punkt ist in anderer ... Irgendwie einen prägnanten Hinweis, dass der Key ausgetauscht werden muss. Bei der Installation.

**Comment by christophboecker** [comment]
Der Hinweis ist wohl nicht deutlich genug.
![grafik](https://user-images.githubusercontent.com/10065904/152802539-52c10f3d-7fa9-4c85-b248-a713dbadbfac.png)

**Comment by christophboecker** [comment]
<img width="766" alt="grafik" src="https://user-images.githubusercontent.com/10065904/152806934-53a8a406-5384-4fea-8743-c757b9cd8d51.png">

**Comment by skerbis** [comment]
Vielleicht auch in die AddOn Beschreibung im Installer?

**Comment by christophboecker** [comment]
Die gibt es ja noch nicht :-). Aber ja, sollte auch dort rein, denn die wird - wie wir alle wissen - ebenso gründlich gelesen und beachtet wie die Readme und das Changelog. <und duck und weg>

**Comment by christophboecker** [comment]
Gefunden. in der Readme steht es drin. In in die Online-Doku kann es noch rein:
<img width="841" alt="grafik" src="https://user-images.githubusercontent.com/10065904/152812808-6ca2f3be-00d7-4332-b1b9-359a8298d6c1.png">
